package domain

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
)

// GenerateComposeFile generates a Docker Compose YAML file from service definitions.
// Only services with a `start` command are included. nginx is always added implicitly.
// The compose file contains ALL startable services — autostart controls which are
// started on create, not which are generated.
func GenerateComposeFile(cfg *ProjectConfig, manifest *Manifest) ([]byte, error) {
	if cfg.Runner == nil || cfg.Runner.Compose == nil {
		return nil, fmt.Errorf("runner.compose is not configured")
	}

	image := cfg.Runner.Compose.Image
	if image == "" {
		return nil, fmt.Errorf("runner.compose.image is required")
	}

	var b strings.Builder

	proxyEnabled := cfg.Runner.Compose.Proxy.IsEnabled()

	b.WriteString("# Generated by previewctl — do not edit\n")
	b.WriteString("services:\n")

	// Proxy (implicit, if enabled)
	if proxyEnabled {
		proxyType := cfg.Runner.Compose.Proxy.ResolvedType()
		switch proxyType {
		case "nginx":
			b.WriteString("  nginx:\n")
			b.WriteString("    image: nginx:alpine\n")
			b.WriteString("    network_mode: host\n")
			b.WriteString("    volumes:\n")
			b.WriteString("      - ./preview/nginx.conf:/etc/nginx/conf.d/default.conf:ro\n")
			b.WriteString("    healthcheck:\n")
			b.WriteString("      test: [\"CMD\", \"curl\", \"-f\", \"http://localhost:80/health\"]\n")
			b.WriteString("      interval: 5s\n")
			b.WriteString("      timeout: 3s\n")
			b.WriteString("      retries: 5\n")
			b.WriteString("    restart: unless-stopped\n")
			b.WriteString("\n")
		default:
			return nil, fmt.Errorf("unsupported proxy type: %s", proxyType)
		}
	}

	// Sort service names for deterministic output
	svcNames := make([]string, 0, len(cfg.Services))
	for name, svc := range cfg.Services {
		if svc.Start != "" {
			svcNames = append(svcNames, name)
		}
	}
	sort.Strings(svcNames)

	for _, name := range svcNames {
		svc := cfg.Services[name]

		// Build env_file paths
		envFile := filepath.Join(svc.Path, ".env")
		envLocalFile := filepath.Join(svc.Path, svc.ResolvedEnvFile())

		fmt.Fprintf(&b, "  %s:\n", name)
		fmt.Fprintf(&b, "    image: %s\n", image)
		b.WriteString("    volumes:\n")
		b.WriteString("      - .:/app\n")
		b.WriteString("    network_mode: host\n")
		fmt.Fprintf(&b, "    working_dir: /app/%s\n", svc.Path)
		fmt.Fprintf(&b, "    command: %s\n", svc.Start)
		b.WriteString("    env_file:\n")
		fmt.Fprintf(&b, "      - %s\n", envFile)
		fmt.Fprintf(&b, "      - %s\n", envLocalFile)
		if proxyEnabled {
			b.WriteString("    depends_on:\n")
			b.WriteString("      nginx:\n")
			b.WriteString("        condition: service_healthy\n")
		}
		b.WriteString("    restart: unless-stopped\n")
		b.WriteString("\n")
	}

	return []byte(b.String()), nil
}
