package domain

import (
	"encoding/json"
	"fmt"
	"io"
	"path/filepath"
	"sort"
)

// Manifest is the single source of truth written to the compute location.
// It contains fully resolved values — no template variables.
type Manifest struct {
	Version            int                          `json:"version"`
	EnvName            string                       `json:"env_name"`
	ProjectName        string                       `json:"project_name"`
	Branch             string                       `json:"branch"`
	Mode               string                       `json:"mode"`
	Ports              PortMap                      `json:"ports"`
	ProvisionerOutputs map[string]map[string]string `json:"provisioner_outputs,omitempty"`
	Services           map[string]ManifestService   `json:"services,omitempty"`
	Infrastructure     *ManifestInfrastructure      `json:"infrastructure,omitempty"`
}

// ManifestService describes a service with fully resolved env vars.
type ManifestService struct {
	Path    string            `json:"path"`
	EnvFile string            `json:"env_file"`
	Env     map[string]string `json:"env,omitempty"`
}

// ManifestInfrastructure describes infrastructure configuration.
type ManifestInfrastructure struct {
	ComposeFile string `json:"compose_file"`
}

// BuildManifest resolves all template variables and builds a complete manifest.
func BuildManifest(
	cfg *ProjectConfig,
	envName, branch, mode string,
	ports PortMap,
	provisionerOutputs map[string]map[string]string,
) (*Manifest, error) {
	// Split ports into service and infrastructure
	servicePorts := make(PortMap)
	infraPorts := make(PortMap)
	for name, port := range ports {
		if _, ok := cfg.Services[name]; ok {
			servicePorts[name] = port
		} else {
			infraPorts[name] = port
		}
	}

	tmplCtx := &TemplateContext{
		ServicePorts:       servicePorts,
		InfraPorts:         infraPorts,
		ProvisionerOutputs: provisionerOutputs,
	}

	// Resolve env vars for each service
	services := make(map[string]ManifestService)
	for svcName, svc := range cfg.Services {
		ms := ManifestService{
			Path:    svc.Path,
			EnvFile: svc.ResolvedEnvFile(),
		}

		if svc.Env != nil {
			tmplCtx.CurrentService = svcName
			rendered, err := RenderEnvMap(svc.Env, tmplCtx)
			if err != nil {
				return nil, fmt.Errorf("rendering env for service '%s': %w", svcName, err)
			}
			ms.Env = rendered
		}

		services[svcName] = ms
	}

	m := &Manifest{
		Version:            1,
		EnvName:            envName,
		ProjectName:        cfg.Name,
		Branch:             branch,
		Mode:               mode,
		Ports:              ports,
		ProvisionerOutputs: provisionerOutputs,
		Services:           services,
	}

	if cfg.Infrastructure != nil && cfg.Infrastructure.ComposeFile != "" {
		m.Infrastructure = &ManifestInfrastructure{
			ComposeFile: cfg.Infrastructure.ComposeFile,
		}
	}

	return m, nil
}

// WriteManifest encodes a manifest as JSON to the given writer.
func WriteManifest(m *Manifest, w io.Writer) error {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	return enc.Encode(m)
}

// ReadManifest decodes a manifest from the given reader.
func ReadManifest(r io.Reader) (*Manifest, error) {
	var m Manifest
	if err := json.NewDecoder(r).Decode(&m); err != nil {
		return nil, fmt.Errorf("decoding manifest: %w", err)
	}
	return &m, nil
}

// RenderEnvFileContent renders a map of env vars to KEY=VALUE format content.
// Keys are sorted for deterministic output.
func RenderEnvFileContent(env map[string]string) []byte {
	keys := make([]string, 0, len(env))
	for k := range env {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var content []byte
	content = append(content, "# Generated by previewctl — do not edit\n"...)
	for _, k := range keys {
		content = append(content, fmt.Sprintf("%s=%s\n", k, env[k])...)
	}
	return content
}

// EnvFilePaths returns a map of relative file paths to env var maps,
// grouping services that share the same env file path.
func (m *Manifest) EnvFilePaths() map[string]map[string]string {
	files := make(map[string]map[string]string)
	for _, svc := range m.Services {
		if svc.Env == nil {
			continue
		}
		target := filepath.Join(svc.Path, svc.EnvFile)
		if _, ok := files[target]; !ok {
			files[target] = make(map[string]string)
		}
		for k, v := range svc.Env {
			files[target][k] = v
		}
	}
	return files
}
