package domain

import (
	"bytes"
	"testing"
)

func TestBuildManifest_ResolvesTemplates(t *testing.T) {
	cfg := &ProjectConfig{
		Name: "myproject",
		Services: map[string]ServiceConfig{
			"backend": {
				Path: "apps/backend",
				Env: map[string]string{
					"PORT":         "{{self.port}}",
					"DATABASE_URL": "{{provisioner.postgres.CONNECTION_STRING}}",
					"WEB_PORT":     "{{services.web.port}}",
					"REDIS_PORT":   "{{infrastructure.redis.port}}",
				},
			},
			"web": {
				Path: "apps/web",
				Env: map[string]string{
					"PORT":    "{{self.port}}",
					"API_URL": "http://localhost:{{services.backend.port}}",
				},
			},
		},
		InfraServices: map[string]InfraService{
			"redis": {Name: "redis", Port: 6379},
		},
		Infrastructure: &InfrastructureConfig{
			ComposeFile: "preview/compose.worktree.yaml",
		},
	}

	ports := PortMap{"backend": 61200, "web": 61201, "redis": 61202}
	provOutputs := map[string]map[string]string{
		"postgres": {"CONNECTION_STRING": "postgresql://localhost:5432/test"},
	}

	m, err := BuildManifest(cfg, "pr-42", "feat/auth", "local", ports, provOutputs)
	if err != nil {
		t.Fatalf("BuildManifest error: %v", err)
	}

	if m.EnvName != "pr-42" {
		t.Errorf("expected env_name 'pr-42', got '%s'", m.EnvName)
	}
	if m.ProjectName != "myproject" {
		t.Errorf("expected project_name 'myproject', got '%s'", m.ProjectName)
	}
	if m.Branch != "feat/auth" {
		t.Errorf("expected branch 'feat/auth', got '%s'", m.Branch)
	}
	if m.Mode != "local" {
		t.Errorf("expected mode 'local', got '%s'", m.Mode)
	}

	// Check backend service env resolution
	backend := m.Services["backend"]
	if backend.Env["PORT"] != "61200" {
		t.Errorf("expected backend PORT=61200, got '%s'", backend.Env["PORT"])
	}
	if backend.Env["DATABASE_URL"] != "postgresql://localhost:5432/test" {
		t.Errorf("expected DATABASE_URL to be resolved, got '%s'", backend.Env["DATABASE_URL"])
	}
	if backend.Env["WEB_PORT"] != "61201" {
		t.Errorf("expected WEB_PORT=61201, got '%s'", backend.Env["WEB_PORT"])
	}
	if backend.Env["REDIS_PORT"] != "61202" {
		t.Errorf("expected REDIS_PORT=61202, got '%s'", backend.Env["REDIS_PORT"])
	}

	// Check web service
	web := m.Services["web"]
	if web.Env["PORT"] != "61201" {
		t.Errorf("expected web PORT=61201, got '%s'", web.Env["PORT"])
	}
	if web.Env["API_URL"] != "http://localhost:61200" {
		t.Errorf("expected API_URL=http://localhost:61200, got '%s'", web.Env["API_URL"])
	}

	// Check infrastructure
	if m.Infrastructure == nil {
		t.Fatal("expected infrastructure to be set")
	}
	if m.Infrastructure.ComposeFile != "preview/compose.worktree.yaml" {
		t.Errorf("expected compose file path, got '%s'", m.Infrastructure.ComposeFile)
	}
}

func TestManifest_JSONRoundTrip(t *testing.T) {
	original := &Manifest{
		Version:     1,
		EnvName:     "test-env",
		ProjectName: "myproject",
		Branch:      "main",
		Mode:        "local",
		Ports:       PortMap{"backend": 8042},
		ProvisionerOutputs: map[string]map[string]string{
			"postgres": {"CONNECTION_STRING": "postgresql://localhost/test"},
		},
		Services: map[string]ManifestService{
			"backend": {
				Path:    "apps/backend",
				EnvFile: ".env.local",
				Env:     map[string]string{"PORT": "8042"},
			},
		},
	}

	var buf bytes.Buffer
	if err := WriteManifest(original, &buf); err != nil {
		t.Fatalf("WriteManifest error: %v", err)
	}

	decoded, err := ReadManifest(&buf)
	if err != nil {
		t.Fatalf("ReadManifest error: %v", err)
	}

	if decoded.EnvName != original.EnvName {
		t.Errorf("expected env_name '%s', got '%s'", original.EnvName, decoded.EnvName)
	}
	if decoded.Ports["backend"] != 8042 {
		t.Errorf("expected port 8042, got %d", decoded.Ports["backend"])
	}
	if decoded.Services["backend"].Env["PORT"] != "8042" {
		t.Errorf("expected PORT=8042, got '%s'", decoded.Services["backend"].Env["PORT"])
	}
}

func TestManifest_EnvFilePaths(t *testing.T) {
	m := &Manifest{
		Services: map[string]ManifestService{
			"backend": {
				Path:    "apps/backend",
				EnvFile: ".env.local",
				Env:     map[string]string{"PORT": "8042", "DB_URL": "pg://localhost"},
			},
			"web": {
				Path:    "apps/web",
				EnvFile: ".env.local",
				Env:     map[string]string{"PORT": "3042"},
			},
			"noenv": {
				Path:    "apps/noenv",
				EnvFile: ".env.local",
			},
		},
	}

	paths := m.EnvFilePaths()
	if len(paths) != 2 {
		t.Errorf("expected 2 env file paths, got %d", len(paths))
	}
	if paths["apps/backend/.env.local"]["PORT"] != "8042" {
		t.Error("expected backend env vars")
	}
	if paths["apps/web/.env.local"]["PORT"] != "3042" {
		t.Error("expected web env vars")
	}
}

func TestRenderEnvFileContent(t *testing.T) {
	content := RenderEnvFileContent(map[string]string{
		"PORT": "8042",
		"API":  "http://localhost",
	})
	s := string(content)
	if s != "# Generated by previewctl — do not edit\nAPI=http://localhost\nPORT=8042\n" {
		t.Errorf("unexpected content:\n%s", s)
	}
}
