package domain

import (
	"fmt"
	"sort"
	"strings"
)

// GenerateNginxConfig generates an nginx configuration file from the manifest
// and service definitions. Services with a `proxy` field get dedicated server
// blocks with the proxy location. All other services use the generic map-based
// routing. nginx is always included with a health check endpoint.
func GenerateNginxConfig(cfg *ProjectConfig, manifest *Manifest, domain string) ([]byte, error) {
	var b strings.Builder

	b.WriteString("# Generated by previewctl — do not edit\n\n")

	// Build the map block for generic routing
	b.WriteString("map $service $upstream_port {\n")
	portNames := make([]string, 0, len(manifest.Ports))
	for name := range manifest.Ports {
		portNames = append(portNames, name)
	}
	sort.Strings(portNames)
	for _, name := range portNames {
		fmt.Fprintf(&b, "    %s %d;\n", name, manifest.Ports[name])
	}
	b.WriteString("}\n\n")

	// Generate per-service server blocks for services with proxy rules
	svcNames := make([]string, 0, len(cfg.Services))
	for name := range cfg.Services {
		svcNames = append(svcNames, name)
	}
	sort.Strings(svcNames)

	for _, name := range svcNames {
		svc := cfg.Services[name]
		if svc.Proxy == nil {
			continue
		}

		svcPort, ok := manifest.Ports[name]
		if !ok {
			continue
		}

		targetPort, ok := manifest.Ports[svc.Proxy.To.Service]
		if !ok {
			return nil, fmt.Errorf("proxy target service '%s' not found in ports", svc.Proxy.To.Service)
		}

		b.WriteString("server {\n")
		b.WriteString("    listen 80;\n")
		fmt.Fprintf(&b, "    server_name %s--%s.%s;\n\n", manifest.EnvName, name, domain)

		// Proxy location
		targetPath := svc.Proxy.ResolvedTargetPath()
		fmt.Fprintf(&b, "    location %s/ {\n", svc.Proxy.Path)
		fmt.Fprintf(&b, "        proxy_pass http://127.0.0.1:%d%s/;\n", targetPort, targetPath)
		b.WriteString("        proxy_http_version 1.1;\n")
		b.WriteString("        proxy_set_header Host localhost;\n")
		b.WriteString("        proxy_set_header X-Forwarded-Host $host;\n")
		b.WriteString("        proxy_set_header X-Forwarded-Proto https;\n")
		b.WriteString("    }\n\n")

		// Default location for the service itself
		b.WriteString("    location / {\n")
		fmt.Fprintf(&b, "        proxy_pass http://127.0.0.1:%d;\n", svcPort)
		b.WriteString("        proxy_http_version 1.1;\n")
		b.WriteString("        proxy_set_header Upgrade $http_upgrade;\n")
		b.WriteString("        proxy_set_header Connection \"upgrade\";\n")
		b.WriteString("        proxy_set_header Host localhost;\n")
		b.WriteString("        proxy_set_header X-Forwarded-Host $host;\n")
		b.WriteString("        proxy_set_header X-Forwarded-Proto https;\n")
		b.WriteString("    }\n")
		b.WriteString("}\n\n")
	}

	// Generic server block for services without proxy rules
	b.WriteString("server {\n")
	b.WriteString("    listen 80;\n")
	fmt.Fprintf(&b, "    server_name ~^.+--.+\\.%s$;\n\n", strings.ReplaceAll(domain, ".", "\\."))
	b.WriteString("    location / {\n")
	b.WriteString("        proxy_pass http://127.0.0.1:$upstream_port;\n")
	b.WriteString("        proxy_http_version 1.1;\n")
	b.WriteString("        proxy_set_header Upgrade $http_upgrade;\n")
	b.WriteString("        proxy_set_header Connection \"upgrade\";\n")
	b.WriteString("        proxy_set_header Host localhost;\n")
	b.WriteString("        proxy_set_header X-Forwarded-Host $host;\n")
	b.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
	b.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
	b.WriteString("        proxy_set_header X-Forwarded-Proto https;\n")
	b.WriteString("    }\n")
	b.WriteString("}\n\n")

	// Default server with health check
	b.WriteString("server {\n")
	b.WriteString("    listen 80 default_server;\n\n")
	b.WriteString("    location /health {\n")
	b.WriteString("        return 200 \"ok\";\n")
	b.WriteString("    }\n\n")
	b.WriteString("    location / {\n")
	b.WriteString("        return 404;\n")
	b.WriteString("    }\n")
	b.WriteString("}\n")

	return []byte(b.String()), nil
}
