package domain

import (
	"fmt"
	"sort"
	"strings"
)

// GenerateNginxConfig generates an nginx configuration file from the manifest
// and service definitions. Each service gets its own server block with explicit
// hostname matching.
//
// Enabled services get full proxy blocks with a custom 502 error page.
// Disabled services (known but not started) get a friendly status page
// telling the user how to start the service.
// Unknown subdomains hit the default server with a 404 page.
func GenerateNginxConfig(cfg *ProjectConfig, manifest *Manifest, domain string) ([]byte, error) {
	var b strings.Builder

	b.WriteString("# Generated by previewctl — do not edit\n")
	b.WriteString("server_names_hash_bucket_size 128;\n\n")

	// Determine which services are enabled
	enabled := make(map[string]bool)
	for _, name := range manifest.EnabledServices {
		enabled[name] = true
	}
	// Fallback: if no enabled services tracked, treat all ported services as enabled
	if len(enabled) == 0 {
		for name := range manifest.Ports {
			enabled[name] = true
		}
	}

	// Sort all service names for deterministic output
	svcNames := make([]string, 0, len(cfg.Services))
	for name := range cfg.Services {
		svcNames = append(svcNames, name)
	}
	sort.Strings(svcNames)

	for _, name := range svcNames {
		port, hasPort := manifest.Ports[name]
		svc := cfg.Services[name]
		serverName := fmt.Sprintf("%s--%s.%s", manifest.EnvName, name, domain)

		if !enabled[name] || !hasPort {
			// Disabled service — return a friendly page
			writeDisabledServerBlock(&b, serverName, manifest.EnvName, name)
			continue
		}

		// Enabled service — full proxy
		b.WriteString("server {\n")
		b.WriteString("    listen 80;\n")
		fmt.Fprintf(&b, "    server_name %s;\n\n", serverName)

		// Custom error pages
		b.WriteString("    error_page 502 /previewctl_502.html;\n")
		b.WriteString("    error_page 503 /previewctl_503.html;\n")
		b.WriteString("    location = /previewctl_502.html {\n")
		b.WriteString("        root /app/preview/error-pages;\n")
		b.WriteString("        internal;\n")
		b.WriteString("    }\n")
		b.WriteString("    location = /previewctl_503.html {\n")
		b.WriteString("        root /app/preview/error-pages;\n")
		b.WriteString("        internal;\n")
		b.WriteString("    }\n\n")

		// Proxy locations (if configured on this service)
		if len(svc.Proxy) > 0 {
			for _, proxy := range svc.Proxy {
				targetPort, ok := manifest.Ports[proxy.To.Service]
				if !ok {
					return nil, fmt.Errorf("proxy target service '%s' not found in ports", proxy.To.Service)
				}
				targetPath := proxy.ResolvedTargetPath()

				fmt.Fprintf(&b, "    location %s/ {\n", proxy.Path)
				fmt.Fprintf(&b, "        proxy_pass http://127.0.0.1:%d%s/;\n", targetPort, targetPath)
				b.WriteString("        proxy_http_version 1.1;\n")
				b.WriteString("        proxy_set_header Host localhost;\n")
				b.WriteString("        proxy_set_header X-Forwarded-Host $host;\n")
				b.WriteString("        proxy_set_header X-Forwarded-Proto https;\n")
				b.WriteString("    }\n\n")
			}
		}

		// Default location for the service itself
		b.WriteString("    location / {\n")
		fmt.Fprintf(&b, "        proxy_pass http://127.0.0.1:%d;\n", port)
		b.WriteString("        proxy_http_version 1.1;\n")
		b.WriteString("        proxy_set_header Upgrade $http_upgrade;\n")
		b.WriteString("        proxy_set_header Connection \"upgrade\";\n")
		b.WriteString("        proxy_set_header Host localhost;\n")
		b.WriteString("        proxy_set_header X-Forwarded-Host $host;\n")
		b.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
		b.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
		b.WriteString("        proxy_set_header X-Forwarded-Proto https;\n")
		b.WriteString("    }\n")
		b.WriteString("}\n\n")
	}

	// Default server with health check + 404 page
	b.WriteString("server {\n")
	b.WriteString("    listen 80 default_server;\n\n")
	b.WriteString("    error_page 404 /previewctl_404.html;\n")
	b.WriteString("    location = /previewctl_404.html {\n")
	b.WriteString("        root /app/preview/error-pages;\n")
	b.WriteString("        internal;\n")
	b.WriteString("    }\n\n")
	b.WriteString("    location /health {\n")
	b.WriteString("        return 200 \"ok\";\n")
	b.WriteString("    }\n\n")
	b.WriteString("    location / {\n")
	b.WriteString("        return 404;\n")
	b.WriteString("    }\n")
	b.WriteString("}\n")

	return []byte(b.String()), nil
}

func writeDisabledServerBlock(b *strings.Builder, serverName, envName, svcName string) {
	b.WriteString("server {\n")
	b.WriteString("    listen 80;\n")
	fmt.Fprintf(b, "    server_name %s;\n\n", serverName)
	b.WriteString("    error_page 503 /previewctl_503.html;\n")
	b.WriteString("    location = /previewctl_503.html {\n")
	b.WriteString("        root /app/preview/error-pages;\n")
	b.WriteString("        internal;\n")
	b.WriteString("    }\n\n")
	b.WriteString("    location / {\n")
	b.WriteString("        return 503;\n")
	b.WriteString("    }\n")
	b.WriteString("}\n\n")
}
