package domain

import (
	"fmt"
	"sort"
	"strings"
)

// GenerateNginxConfig generates an nginx configuration file from the manifest
// and service definitions. Each service gets its own server block with explicit
// hostname matching. Services with a `proxy` field get an additional location
// block for the proxy path.
func GenerateNginxConfig(cfg *ProjectConfig, manifest *Manifest, domain string) ([]byte, error) {
	var b strings.Builder

	b.WriteString("# Generated by previewctl — do not edit\n")
	b.WriteString("server_names_hash_bucket_size 128;\n\n")

	// Sort service names for deterministic output
	svcNames := make([]string, 0, len(manifest.Ports))
	for name := range manifest.Ports {
		svcNames = append(svcNames, name)
	}
	sort.Strings(svcNames)

	for _, name := range svcNames {
		port := manifest.Ports[name]
		svc, hasSvcConfig := cfg.Services[name]

		b.WriteString("server {\n")
		b.WriteString("    listen 80;\n")
		fmt.Fprintf(&b, "    server_name %s--%s.%s;\n\n", manifest.EnvName, name, domain)

		// Proxy locations (if configured on this service)
		if hasSvcConfig && len(svc.Proxy) > 0 {
			for _, proxy := range svc.Proxy {
				targetPort, ok := manifest.Ports[proxy.To.Service]
				if !ok {
					return nil, fmt.Errorf("proxy target service '%s' not found in ports", proxy.To.Service)
				}
				targetPath := proxy.ResolvedTargetPath()

				fmt.Fprintf(&b, "    location %s/ {\n", proxy.Path)
				fmt.Fprintf(&b, "        proxy_pass http://127.0.0.1:%d%s/;\n", targetPort, targetPath)
				b.WriteString("        proxy_http_version 1.1;\n")
				b.WriteString("        proxy_set_header Host localhost;\n")
				b.WriteString("        proxy_set_header X-Forwarded-Host $host;\n")
				b.WriteString("        proxy_set_header X-Forwarded-Proto https;\n")
				b.WriteString("    }\n\n")
			}
		}

		// Default location for the service itself
		b.WriteString("    location / {\n")
		fmt.Fprintf(&b, "        proxy_pass http://127.0.0.1:%d;\n", port)
		b.WriteString("        proxy_http_version 1.1;\n")
		b.WriteString("        proxy_set_header Upgrade $http_upgrade;\n")
		b.WriteString("        proxy_set_header Connection \"upgrade\";\n")
		b.WriteString("        proxy_set_header Host localhost;\n")
		b.WriteString("        proxy_set_header X-Forwarded-Host $host;\n")
		b.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
		b.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
		b.WriteString("        proxy_set_header X-Forwarded-Proto https;\n")
		b.WriteString("    }\n")
		b.WriteString("}\n\n")
	}

	// Default server with health check
	b.WriteString("server {\n")
	b.WriteString("    listen 80 default_server;\n\n")
	b.WriteString("    location /health {\n")
	b.WriteString("        return 200 \"ok\";\n")
	b.WriteString("    }\n\n")
	b.WriteString("    location / {\n")
	b.WriteString("        return 404;\n")
	b.WriteString("    }\n")
	b.WriteString("}\n")

	return []byte(b.String()), nil
}
