package local

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/jake-landersweb/previewctl/src/domain"
)

// EnvGenAdapter implements domain.EnvPort for local development.
// It generates .env.local files for each service and symlinks shared env files.
type EnvGenAdapter struct {
	config *domain.ProjectConfig
}

// NewEnvGenAdapter creates a new local env generation adapter.
func NewEnvGenAdapter(config *domain.ProjectConfig) *EnvGenAdapter {
	return &EnvGenAdapter{config: config}
}

func (a *EnvGenAdapter) Generate(_ context.Context, envName string, workdir string, ports domain.PortMap, coreOutputs map[string]map[string]string) error {
	// Split ports into service and infrastructure
	servicePorts := make(domain.PortMap)
	infraPorts := make(domain.PortMap)
	for name, port := range ports {
		if _, ok := a.config.Services[name]; ok {
			servicePorts[name] = port
		} else {
			infraPorts[name] = port
		}
	}

	ctx := &domain.TemplateContext{
		ServicePorts: servicePorts,
		InfraPorts:   infraPorts,
		CoreOutputs:  coreOutputs,
	}

	// Group env vars by target file path (service path + env_file)
	fileEnvs := make(map[string]map[string]string)
	for svcName, svc := range a.config.Services {
		if svc.Env == nil {
			continue
		}
		ctx.CurrentService = svcName
		rendered, err := domain.RenderEnvMap(svc.Env, ctx)
		if err != nil {
			return fmt.Errorf("rendering env for service: %w", err)
		}
		target := filepath.Join(svc.Path, svc.ResolvedEnvFile())
		if _, ok := fileEnvs[target]; !ok {
			fileEnvs[target] = make(map[string]string)
		}
		for k, v := range rendered {
			fileEnvs[target][k] = v
		}
	}

	// Write env files
	for relPath, envVars := range fileEnvs {
		envFilePath := filepath.Join(workdir, relPath)
		if err := writeEnvFile(envFilePath, envVars); err != nil {
			return fmt.Errorf("writing %s: %w", envFilePath, err)
		}
	}

	return nil
}

func (a *EnvGenAdapter) SymlinkSharedEnvFiles(_ context.Context, workdir string) error {
	if a.config.Local == nil || len(a.config.Local.Worktree.SymlinkPatterns) == 0 {
		return nil
	}

	mainWorktree, err := findMainWorktree()
	if err != nil {
		return fmt.Errorf("finding main worktree: %w", err)
	}

	// Walk the main worktree and find files matching any pattern
	return filepath.Walk(mainWorktree, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil // skip inaccessible paths
		}

		// Skip directories, .git, and node_modules
		if info.IsDir() {
			name := info.Name()
			if name == ".git" || name == "node_modules" || name == ".next" || name == "dist" || name == "build" {
				return filepath.SkipDir
			}
			return nil
		}

		// Check if the filename matches any pattern
		matched := false
		for _, pattern := range a.config.Local.Worktree.SymlinkPatterns {
			if m, _ := filepath.Match(pattern, info.Name()); m {
				matched = true
				break
			}
		}
		if !matched {
			return nil
		}

		// Compute relative path from main worktree
		relPath, err := filepath.Rel(mainWorktree, path)
		if err != nil {
			return nil
		}

		// Skip files tracked by git — they already exist in the worktree via checkout
		if isGitTracked(mainWorktree, relPath) {
			return nil
		}

		dst := filepath.Join(workdir, relPath)

		// Skip if source and destination are the same file
		if path == dst {
			return nil
		}

		// Ensure destination directory exists
		if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
			return fmt.Errorf("creating directory for %s: %w", relPath, err)
		}

		// Remove existing file/symlink at destination
		_ = os.Remove(dst)

		if err := os.Symlink(path, dst); err != nil {
			return fmt.Errorf("symlinking %s: %w", relPath, err)
		}

		return nil
	})
}

func (a *EnvGenAdapter) Cleanup(_ context.Context, workdir string) error {
	// Remove generated env files
	targets := make(map[string]bool)
	for _, svc := range a.config.Services {
		target := filepath.Join(svc.Path, svc.ResolvedEnvFile())
		targets[target] = true
	}

	for relPath := range targets {
		envFilePath := filepath.Join(workdir, relPath)
		_ = os.Remove(envFilePath) // ignore errors for missing files
	}

	return nil
}

// writeEnvFile writes a map of env vars to a file in KEY=VALUE format.
func writeEnvFile(path string, envVars map[string]string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	// Sort keys for deterministic output
	keys := make([]string, 0, len(envVars))
	for k := range envVars {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var sb strings.Builder
	sb.WriteString("# Generated by previewctl — do not edit\n")
	for _, k := range keys {
		fmt.Fprintf(&sb, "%s=%s\n", k, envVars[k])
	}

	return os.WriteFile(path, []byte(sb.String()), 0o644)
}

// isGitTracked checks if a file is tracked by git.
func isGitTracked(repoDir string, relPath string) bool {
	cmd := exec.Command("git", "ls-files", "--error-unmatch", relPath)
	cmd.Dir = repoDir
	return cmd.Run() == nil
}

// findMainWorktree returns the path of the main git worktree.
func findMainWorktree() (string, error) {
	// Use git to find the main worktree — works from any worktree or the main repo
	cmd := exec.Command("git", "worktree", "list", "--porcelain")
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("running git worktree list: %w", err)
	}

	// The first "worktree <path>" line is always the main worktree
	for _, line := range strings.Split(string(out), "\n") {
		if strings.HasPrefix(line, "worktree ") {
			return strings.TrimPrefix(line, "worktree "), nil
		}
	}

	return "", fmt.Errorf("could not determine main git worktree")
}
