package local

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/jake-landersweb/previewctl/src/domain"
)

// EnvGenAdapter implements domain.EnvPort for local development.
// It generates .env.local files for each service and symlinks shared env files.
type EnvGenAdapter struct {
	config *domain.ProjectConfig
}

// NewEnvGenAdapter creates a new local env generation adapter.
func NewEnvGenAdapter(config *domain.ProjectConfig) *EnvGenAdapter {
	return &EnvGenAdapter{config: config}
}

func (a *EnvGenAdapter) Generate(_ context.Context, envName string, workdir string, ports domain.PortMap, provisionerOutputs map[string]map[string]string) error {
	// Split ports into service and infrastructure
	servicePorts := make(domain.PortMap)
	infraPorts := make(domain.PortMap)
	for name, port := range ports {
		if _, ok := a.config.Services[name]; ok {
			servicePorts[name] = port
		} else {
			infraPorts[name] = port
		}
	}

	ctx := &domain.TemplateContext{
		ServicePorts:       servicePorts,
		InfraPorts:         infraPorts,
		ProvisionerOutputs: provisionerOutputs,
	}

	// Group env vars by target file path (service path + env_file)
	fileEnvs := make(map[string]map[string]string)
	for svcName, svc := range a.config.Services {
		if svc.Env == nil {
			continue
		}
		ctx.CurrentService = svcName
		rendered, err := domain.RenderEnvMap(svc.Env, ctx)
		if err != nil {
			return fmt.Errorf("rendering env for service: %w", err)
		}
		target := filepath.Join(svc.Path, svc.ResolvedEnvFile())
		if _, ok := fileEnvs[target]; !ok {
			fileEnvs[target] = make(map[string]string)
		}
		for k, v := range rendered {
			fileEnvs[target][k] = v
		}
	}

	// Write env files
	for relPath, envVars := range fileEnvs {
		envFilePath := filepath.Join(workdir, relPath)
		if err := writeEnvFile(envFilePath, envVars); err != nil {
			return fmt.Errorf("writing %s: %w", envFilePath, err)
		}
	}

	return nil
}

func (a *EnvGenAdapter) Cleanup(_ context.Context, workdir string) error {
	// Remove generated env files
	targets := make(map[string]bool)
	for _, svc := range a.config.Services {
		target := filepath.Join(svc.Path, svc.ResolvedEnvFile())
		targets[target] = true
	}

	for relPath := range targets {
		envFilePath := filepath.Join(workdir, relPath)
		_ = os.Remove(envFilePath) // ignore errors for missing files
	}

	return nil
}

// writeEnvFile writes a map of env vars to a file in KEY=VALUE format.
func writeEnvFile(path string, envVars map[string]string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	// Sort keys for deterministic output
	keys := make([]string, 0, len(envVars))
	for k := range envVars {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var sb strings.Builder
	sb.WriteString("# Generated by previewctl — do not edit\n")
	for _, k := range keys {
		fmt.Fprintf(&sb, "%s=%s\n", k, envVars[k])
	}

	return os.WriteFile(path, []byte(sb.String()), 0o644)
}
