package local

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/jake-landersweb/previewctl/src/domain"
)

// EnvGenAdapter implements domain.EnvPort for local development.
// It generates .env.local files for each service and symlinks shared env files.
type EnvGenAdapter struct {
	config *domain.ProjectConfig
}

// NewEnvGenAdapter creates a new local env generation adapter.
func NewEnvGenAdapter(config *domain.ProjectConfig) *EnvGenAdapter {
	return &EnvGenAdapter{config: config}
}

func (a *EnvGenAdapter) Generate(_ context.Context, envName string, workdir string, ports domain.PortMap, databases map[string]*domain.DatabaseInfo) error {
	ctx := &domain.TemplateContext{
		Ports:     ports,
		Databases: databases,
	}

	// Group services by path to combine env vars for services sharing a directory
	pathEnvs := make(map[string]map[string]string)
	for _, svc := range a.config.Services {
		if svc.Env == nil {
			continue
		}
		rendered, err := domain.RenderEnvMap(svc.Env, ctx)
		if err != nil {
			return fmt.Errorf("rendering env for service: %w", err)
		}
		if _, ok := pathEnvs[svc.Path]; !ok {
			pathEnvs[svc.Path] = make(map[string]string)
		}
		for k, v := range rendered {
			pathEnvs[svc.Path][k] = v
		}
	}

	// Write .env.local for each unique service path
	for svcPath, envVars := range pathEnvs {
		envFilePath := filepath.Join(workdir, svcPath, ".env.local")
		if err := writeEnvFile(envFilePath, envVars); err != nil {
			return fmt.Errorf("writing %s: %w", envFilePath, err)
		}
	}

	return nil
}

func (a *EnvGenAdapter) SymlinkSharedEnvFiles(_ context.Context, workdir string) error {
	if a.config.Local == nil || len(a.config.Local.Worktree.SymlinkPatterns) == 0 {
		return nil
	}

	mainWorktree, err := findMainWorktree()
	if err != nil {
		return fmt.Errorf("finding main worktree: %w", err)
	}

	// Walk the main worktree and find files matching any pattern
	return filepath.Walk(mainWorktree, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil // skip inaccessible paths
		}

		// Skip directories, .git, and node_modules
		if info.IsDir() {
			name := info.Name()
			if name == ".git" || name == "node_modules" || name == ".next" || name == "dist" || name == "build" {
				return filepath.SkipDir
			}
			return nil
		}

		// Check if the filename matches any pattern
		matched := false
		for _, pattern := range a.config.Local.Worktree.SymlinkPatterns {
			if m, _ := filepath.Match(pattern, info.Name()); m {
				matched = true
				break
			}
		}
		if !matched {
			return nil
		}

		// Compute relative path from main worktree
		relPath, err := filepath.Rel(mainWorktree, path)
		if err != nil {
			return nil
		}

		// Skip files tracked by git — they already exist in the worktree via checkout
		if isGitTracked(mainWorktree, relPath) {
			return nil
		}

		dst := filepath.Join(workdir, relPath)

		// Skip if source and destination are the same file
		if path == dst {
			return nil
		}

		// Ensure destination directory exists
		if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
			return fmt.Errorf("creating directory for %s: %w", relPath, err)
		}

		// Remove existing file/symlink at destination
		os.Remove(dst)

		if err := os.Symlink(path, dst); err != nil {
			return fmt.Errorf("symlinking %s: %w", relPath, err)
		}

		return nil
	})
}

func (a *EnvGenAdapter) Cleanup(_ context.Context, workdir string) error {
	// Remove generated .env.local files
	paths := make(map[string]bool)
	for _, svc := range a.config.Services {
		paths[svc.Path] = true
	}

	for svcPath := range paths {
		envFilePath := filepath.Join(workdir, svcPath, ".env.local")
		os.Remove(envFilePath) // ignore errors for missing files
	}

	return nil
}

// writeEnvFile writes a map of env vars to a file in KEY=VALUE format.
func writeEnvFile(path string, envVars map[string]string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	// Sort keys for deterministic output
	keys := make([]string, 0, len(envVars))
	for k := range envVars {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var sb strings.Builder
	sb.WriteString("# Generated by previewctl — do not edit\n")
	for _, k := range keys {
		sb.WriteString(fmt.Sprintf("%s=%s\n", k, envVars[k]))
	}

	return os.WriteFile(path, []byte(sb.String()), 0o644)
}

// isGitTracked checks if a file is tracked by git.
func isGitTracked(repoDir string, relPath string) bool {
	cmd := exec.Command("git", "ls-files", "--error-unmatch", relPath)
	cmd.Dir = repoDir
	return cmd.Run() == nil
}

// findMainWorktree returns the path of the main git worktree.
func findMainWorktree() (string, error) {
	// Use git to find the main worktree — works from any worktree or the main repo
	cmd := exec.Command("git", "worktree", "list", "--porcelain")
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("running git worktree list: %w", err)
	}

	// The first "worktree <path>" line is always the main worktree
	for _, line := range strings.Split(string(out), "\n") {
		if strings.HasPrefix(line, "worktree ") {
			return strings.TrimPrefix(line, "worktree "), nil
		}
	}

	return "", fmt.Errorf("could not determine main git worktree")
}
